name: build

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
jobs:
  test:
    strategy:
      matrix:
        os: [darwin, linux, windows]
        include:
          - os: darwin
            runner: macos-latest
            no_docker: "true"
            pack_bin: pack
          - os: linux
            runner: ubuntu-latest
            no_docker: "false"
            pack_bin: pack
          - os: windows
            runner: windows-latest
            # disabled because not non-applicable tests are gated
            no_docker: "true"
            pack_bin: pack.exe
    runs-on: ${{ matrix.runner }}
    env:
      PACK_BIN: ${{ matrix.pack_bin }}
      NO_DOCKER: ${{ matrix.no_docker }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.13'
      - name: Set up go env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
        shell: bash
      - name: Verify
        # disabled for windows due verification failing
        if: matrix.os != 'windows'
        run: make verify
      - name: Test
        run: make test
      - name: Build
        run: make build
      - uses: actions/upload-artifact@v1
        with:
          name: pack-${{ matrix.os }}
          path: out/${{ env.PACK_BIN }}